### ISSUE TITLE
Release of assets for darwin/arm64 and windows/arm64 failed at 0.4.0

### ISSUE THREAD

**Issue by suzuki-shunsuke** [zix99/rare#113]
https://github.com/zix99/rare/releases/tag/0.4.0

Assets for darwin/arm64 and windows/arm64 weren't released.

<img width="374" alt="image" src="https://github.com/user-attachments/assets/2d863013-a3fe-4df9-aaa2-59c55bae4aea" />

https://github.com/zix99/rare/actions/runs/12401688033/job/34621582756

GoReleaser outputted deprecation warning.

```
         • DEPRECATED: skipped darwin/arm64 build on Go < 1.16 for compatibility, check https://goreleaser.com/deprecations/#builds-for-darwinarm64 for more info.
         • DEPRECATED: skipped windows/arm64 build on Go < 1.17 for compatibility, check https://goreleaser.com/deprecations/#builds-for-windowsarm64 for more info.
```

- https://goreleaser.com/deprecations/#builds-for-darwinarm64
- https://goreleaser.com/deprecations/#builds-for-windowsarm64

I've created a pull request to resolve this issue.

- https://github.com/zix99/rare/pull/112

**Comment by farzadmf** [comment]
Getting an error in `brew`:

```
Error: zix99/rare/rare: formula requires at least a URL
```

I _think_ it could be related? 🤔

**Comment by suzuki-shunsuke** [comment]
> Getting an error in brew:

I could reproduce the issue on my M1 Pro (darwin/arm64).

```console
$ brew install zix99/rare/rare
Error: zix99/rare/rare: formula requires at least a URL
Warning: Removed Sorbet lines from backtrace!
Rerun with `--verbose` to see the original backtrace
/opt/homebrew/Library/Homebrew/formula.rb:322:in `determine_active_spec'
/opt/homebrew/Library/Homebrew/formula.rb:256:in `initialize'
/opt/homebrew/Library/Homebrew/formulary.rb:568:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:777:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:980:in `factory'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:328:in `block in load_formula_or_cask'
/opt/homebrew/Library/Homebrew/api.rb:203:in `with_no_api_env_if_needed'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:320:in `load_formula_or_cask'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:83:in `block in to_formulae_and_casks'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:81:in `each'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:81:in `flat_map'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:81:in `to_formulae_and_casks'
/opt/homebrew/Library/Homebrew/cmd/install.rb:196:in `run'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
Please report this issue:
  https://docs.brew.sh/Troubleshooting
```

At 0.4.0, darwin/arm64 was removed from Formula.

https://github.com/zix99/homebrew-rare/commit/b0a25861bb31771c71870b772716dd5eb7761725

**Comment by farzadmf** [comment]
Wow, what happened? 😄

@zix99 was the intentional?

**Comment by suzuki-shunsuke** [comment]
> was the intentional?

I'm not a maintainer, but I don't think so.
GoReleaser skipped darwin/arm64. https://github.com/zix99/rare/issues/113#issue-2749450475
So darwin/arm64 was removed from Formula.

```
         • DEPRECATED: skipped darwin/arm64 build on Go < 1.16 for compatibility, check https://goreleaser.com/deprecations/#builds-for-darwinarm64 for more info.
```

**Comment by farzadmf** [comment]
Yeah, @suzuki-shunsuke , saw the PR; hopefully @zix99 will merge it soon

**Comment by zix99** [comment]
Thanks for reporting and creating a PR so quickly.  Not sure how this slipped through.  I'll take a look this afternoon and hopefully merge!

**Comment by zix99** [comment]
@farzadmf merged and re-releasing 0.4.0 now.  Give me a few minutes, then let me know if you continue to have any issues.  I won't be able to test the brew until later

**Comment by suzuki-shunsuke** [comment]
Thank you. brew worked for me.

```console
$ brew install zix99/rare/rare            
==> Fetching zix99/rare/rare
==> Downloading https://github.com/zix99/rare/releases/download/0.4.0/rare_0.4.0_Darwin_arm64.tar.gz
Already downloaded: /Users/shunsukesuzuki/Library/Caches/Homebrew/downloads/889a78ab51bdb9345ba6669c47cc54ebbd23a1ae3c72211310f293028b8792eb--rare_0.4.0_Darwin_arm64.tar.gz
==> Installing rare from zix99/rare
🍺  /opt/homebrew/Cellar/rare/0.4.0: 7 files, 4.4MB, built in 0 seconds
==> Running `brew cleanup rare`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
```

**Comment by farzadmf** [comment]
Thank you @zix99 ; the issue seems to be fixed now
